
exports.addBatchImpl = (sql) => (p_) => () => {
  return p_.addBatch(sql);
}

exports.cancelImpl = (p_) => () => {
  return p_.cancel();
}

exports.clearBatchImpl = (p_) => () => {
  return p_.clearBatch();
}

exports.clearWarningsImpl = (p_) => () => {
  return p_.clearWarnings();
}

exports.closeImpl = (p_) => () => {
  return p_.close();
}

exports.executeWithStringImpl = (sql) => (p_) => () => {
  return p_.execute(sql);
}

exports.executeWithStringIntegerImpl = (sql) => (autoGeneratedKeys) => (p_) => () => {
  return p_.execute(sql, autoGeneratedKeys);
}

exports.executeWithStringStringarrayImpl = (sql) => (columnNames) => (p_) => () => {
  return p_.execute(sql, columnNames);
}

exports.executeBatchImpl = (p_) => () => {
  return p_.executeBatch();
}

exports.executeQueryImpl = (sql) => (p_) => () => {
  return p_.executeQuery(sql);
}

exports.executeUpdateWithStringImpl = (sql) => (p_) => () => {
  return p_.executeUpdate(sql);
}

exports.executeUpdateWithStringIntegerImpl = (sql) => (autoGeneratedKeys) => (p_) => () => {
  return p_.executeUpdate(sql, autoGeneratedKeys);
}

exports.executeUpdateWithStringStringarrayImpl = (sql) => (columnNames) => (p_) => () => {
  return p_.executeUpdate(sql, columnNames);
}

exports.getConnectionImpl = (p_) => () => {
  return p_.getConnection();
}

exports.getFetchDirectionImpl = (p_) => () => {
  return p_.getFetchDirection();
}

exports.getFetchSizeImpl = (p_) => () => {
  return p_.getFetchSize();
}

exports.getGeneratedKeysImpl = (p_) => () => {
  return p_.getGeneratedKeys();
}

exports.getMaxFieldSizeImpl = (p_) => () => {
  return p_.getMaxFieldSize();
}

exports.getMaxRowsImpl = (p_) => () => {
  return p_.getMaxRows();
}

exports.getMoreResultsImpl = (p_) => () => {
  return p_.getMoreResults();
}

exports.getMoreResultsWithIntegerImpl = (current) => (p_) => () => {
  return p_.getMoreResults(current);
}

exports.getQueryTimeoutImpl = (p_) => () => {
  return p_.getQueryTimeout();
}

exports.getResultSetImpl = (p_) => () => {
  return p_.getResultSet();
}

exports.getResultSetConcurrencyImpl = (p_) => () => {
  return p_.getResultSetConcurrency();
}

exports.getResultSetHoldabilityImpl = (p_) => () => {
  return p_.getResultSetHoldability();
}

exports.getResultSetTypeImpl = (p_) => () => {
  return p_.getResultSetType();
}

exports.getUpdateCountImpl = (p_) => () => {
  return p_.getUpdateCount();
}

exports.getWarningsImpl = (p_) => () => {
  return p_.getWarnings();
}

exports.isClosedImpl = (p_) => () => {
  return p_.isClosed();
}

exports.isPoolableImpl = (p_) => () => {
  return p_.isPoolable();
}

exports.setCursorNameImpl = (name) => (p_) => () => {
  return p_.setCursorName(name);
}

exports.setEscapeProcessingImpl = (enable) => (p_) => () => {
  return p_.setEscapeProcessing(enable);
}

exports.setFetchDirectionImpl = (direction) => (p_) => () => {
  return p_.setFetchDirection(direction);
}

exports.setFetchSizeImpl = (rows) => (p_) => () => {
  return p_.setFetchSize(rows);
}

exports.setMaxFieldSizeImpl = (max) => (p_) => () => {
  return p_.setMaxFieldSize(max);
}

exports.setMaxRowsImpl = (max) => (p_) => () => {
  return p_.setMaxRows(max);
}

exports.setPoolableImpl = (poolable) => (p_) => () => {
  return p_.setPoolable(poolable);
}

exports.setQueryTimeoutImpl = (seconds) => (p_) => () => {
  return p_.setQueryTimeout(seconds);
}
